import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../../core/theme/colors.dart';
import '../../../../core/theme/tokens.dart';
import '../../../../core/theme/typography.dart';
import '../../../../core/widgets/buttons/primary_button.dart';
import '../../../../core/widgets/buttons/secondary_button.dart';
import '../domain/entities/prescription.dart';
import 'providers.dart';

class PrescriptionEditorScreen extends ConsumerStatefulWidget {
  final String patientId;
  final String? patientName;

  const PrescriptionEditorScreen({
    super.key,
    required this.patientId,
    this.patientName,
  });

  @override
  ConsumerState<PrescriptionEditorScreen> createState() =>
      _PrescriptionEditorScreenState();
}

class _PrescriptionEditorScreenState
    extends ConsumerState<PrescriptionEditorScreen> {
  final _formKey = GlobalKey<FormState>();
  final _diagnosisController = TextEditingController();
  final _notesController = TextEditingController();

  bool _isLoading = false;

  @override
  void dispose() {
    _diagnosisController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  void _addMedication() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      builder: (context) => _MedicationForm(
        onSave: (medication) {
          final current = ref.read(medicationsProvider);
          ref.read(medicationsProvider.notifier).state = [...current, medication];
        },
      ),
    );
  }

  Future<void> _savePrescription() async {
    if (!_formKey.currentState!.validate()) return;

    final medications = ref.read(medicationsProvider);
    if (medications.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please add at least one medication'),
          backgroundColor: AppColors.error,
        ),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      final prescription = Prescription(
        id: '', // Will be generated by backend
        patientId: widget.patientId,
        doctorId: '', // Will be set from current user
        prescribedAt: DateTime.now(),
        medications: medications,
        diagnosis: _diagnosisController.text.trim(),
        notes: _notesController.text.trim().isEmpty
            ? null
            : _notesController.text.trim(),
      );

      await ref
          .read(prescriptionRepositoryProvider)
          .createPrescription(prescription);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Prescription created successfully'),
            backgroundColor: AppColors.success,
          ),
        );
        context.pop();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(e.toString()),
            backgroundColor: AppColors.error,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final medications = ref.watch(medicationsProvider);

    return Scaffold(
      appBar: AppBar(
        title: const Text('New Prescription'),
      ),
      body: Form(
        key: _formKey,
        child: Column(
          children: [
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(AppTokens.space16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Patient Info
                    if (widget.patientName != null) ...[
                      Card(
                        elevation: AppTokens.elevationSm,
                        child: Padding(
                          padding: const EdgeInsets.all(AppTokens.space16),
                          child: Row(
                            children: [
                              const Icon(
                                Icons.person_outline,
                                color: AppColors.primary,
                              ),
                              const SizedBox(width: AppTokens.space12),
                              Text(
                                widget.patientName!,
                                style: AppTypography.h6,
                              ),
                            ],
                          ),
                        ),
                      ),
                      const SizedBox(height: AppTokens.space24),
                    ],

                    // Diagnosis
                    Text('Diagnosis', style: AppTypography.labelLarge),
                    const SizedBox(height: AppTokens.space8),
                    TextFormField(
                      controller: _diagnosisController,
                      maxLines: 2,
                      decoration: const InputDecoration(
                        hintText: 'Enter diagnosis...',
                      ),
                      validator: (value) {
                        if (value == null || value.isEmpty) {
                          return 'Please enter diagnosis';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: AppTokens.space24),

                    // Medications
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text('Medications', style: AppTypography.h6),
                        TextButton.icon(
                          onPressed: _addMedication,
                          icon: const Icon(Icons.add),
                          label: const Text('Add'),
                        ),
                      ],
                    ),
                    const SizedBox(height: AppTokens.space12),

                    if (medications.isEmpty)
                      Card(
                        elevation: AppTokens.elevationSm,
                        child: Padding(
                          padding: const EdgeInsets.all(AppTokens.space24),
                          child: Center(
                            child: Column(
                              children: [
                                Icon(
                                  Icons.medication_outlined,
                                  size: 48,
                                  color: AppColors.gray300,
                                ),
                                const SizedBox(height: AppTokens.space12),
                                Text(
                                  'No medications added yet',
                                  style: AppTypography.bodyMedium.copyWith(
                                    color: AppColors.textSecondary,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      )
                    else
                      ListView.separated(
                        shrinkWrap: true,
                        physics: const NeverScrollableScrollPhysics(),
                        itemCount: medications.length,
                        separatorBuilder: (_, __) =>
                            const SizedBox(height: AppTokens.space12),
                        itemBuilder: (context, index) {
                          return _MedicationCard(
                            medication: medications[index],
                            onDelete: () {
                              final updated = List<Medication>.from(medications)
                                ..removeAt(index);
                              ref.read(medicationsProvider.notifier).state = updated;
                            },
                          );
                        },
                      ),

                    const SizedBox(height: AppTokens.space24),

                    // Notes
                    Text('Additional Notes (Optional)', style: AppTypography.labelLarge),
                    const SizedBox(height: AppTokens.space8),
                    TextFormField(
                      controller: _notesController,
                      maxLines: 3,
                      decoration: const InputDecoration(
                        hintText: 'Any special instructions...',
                      ),
                    ),
                  ],
                ),
              ),
            ),

            // Action Buttons
            Container(
              padding: const EdgeInsets.all(AppTokens.space16),
              decoration: BoxDecoration(
                color: AppColors.surface,
                boxShadow: [
                  BoxShadow(
                    color: AppColors.gray200,
                    blurRadius: 4,
                    offset: const Offset(0, -2),
                  ),
                ],
              ),
              child: SafeArea(
                child: Column(
                  children: [
                    PrimaryButton(
                      label: 'Save Prescription',
                      onPressed: _isLoading ? null : _savePrescription,
                      isLoading: _isLoading,
                      fullWidth: true,
                    ),
                    const SizedBox(height: AppTokens.space12),
                    SecondaryButton(
                      label: 'Cancel',
                      onPressed: _isLoading ? null : () => context.pop(),
                      fullWidth: true,
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// ═══════════════════════════════════════════════════════════════
// MEDICATION FORM (Bottom Sheet)
// ═══════════════════════════════════════════════════════════════

class _MedicationForm extends StatefulWidget {
  final Function(Medication) onSave;

  const _MedicationForm({required this.onSave});

  @override
  State<_MedicationForm> createState() => _MedicationFormState();
}

class _MedicationFormState extends State<_MedicationForm> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _dosageController = TextEditingController();
  final _frequencyController = TextEditingController();
  final _durationController = TextEditingController();
  final _instructionsController = TextEditingController();

  @override
  void dispose() {
    _nameController.dispose();
    _dosageController.dispose();
    _frequencyController.dispose();
    _durationController.dispose();
    _instructionsController.dispose();
    super.dispose();
  }

  void _save() {
    if (!_formKey.currentState!.validate()) return;

    final medication = Medication(
      name: _nameController.text.trim(),
      dosage: _dosageController.text.trim(),
      frequency: _frequencyController.text.trim(),
      duration: _durationController.text.trim(),
      instructions: _instructionsController.text.trim().isEmpty
          ? null
          : _instructionsController.text.trim(),
    );

    widget.onSave(medication);
    Navigator.pop(context);
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.only(
        bottom: MediaQuery.of(context).viewInsets.bottom,
      ),
      child: SingleChildScrollView(
        padding: const EdgeInsets.all(AppTokens.space24),
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('Add Medication', style: AppTypography.h5),
              const SizedBox(height: AppTokens.space24),

              TextFormField(
                controller: _nameController,
                decoration: const InputDecoration(labelText: 'Medicine Name'),
                validator: (v) => v?.isEmpty ?? true ? 'Required' : null,
              ),
              const SizedBox(height: AppTokens.space16),

              TextFormField(
                controller: _dosageController,
                decoration: const InputDecoration(
                  labelText: 'Dosage',
                  hintText: 'e.g., 500mg',
                ),
                validator: (v) => v?.isEmpty ?? true ? 'Required' : null,
              ),
              const SizedBox(height: AppTokens.space16),

              TextFormField(
                controller: _frequencyController,
                decoration: const InputDecoration(
                  labelText: 'Frequency',
                  hintText: 'e.g., Twice daily',
                ),
                validator: (v) => v?.isEmpty ?? true ? 'Required' : null,
              ),
              const SizedBox(height: AppTokens.space16),

              TextFormField(
                controller: _durationController,
                decoration: const InputDecoration(
                  labelText: 'Duration',
                  hintText: 'e.g., 7 days',
                ),
                validator: (v) => v?.isEmpty ?? true ? 'Required' : null,
              ),
              const SizedBox(height: AppTokens.space16),

              TextFormField(
                controller: _instructionsController,
                maxLines: 2,
                decoration: const InputDecoration(
                  labelText: 'Instructions (Optional)',
                  hintText: 'e.g., Take after meals',
                ),
              ),
              const SizedBox(height: AppTokens.space24),

              Row(
                children: [
                  Expanded(
                    child: SecondaryButton(
                      label: 'Cancel',
                      onPressed: () => Navigator.pop(context),
                    ),
                  ),
                  const SizedBox(width: AppTokens.space12),
                  Expanded(
                    child: PrimaryButton(
                      label: 'Add',
                      onPressed: _save,
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}

// ═══════════════════════════════════════════════════════════════
// MEDICATION CARD
// ═══════════════════════════════════════════════════════════════

class _MedicationCard extends StatelessWidget {
  final Medication medication;
  final VoidCallback onDelete;

  const _MedicationCard({
    required this.medication,
    required this.onDelete,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: AppTokens.elevationSm,
      child: Padding(
        padding: const EdgeInsets.all(AppTokens.space16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Expanded(
                  child: Text(
                    medication.name,
                    style: AppTypography.h6,
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.delete_outline, size: AppTokens.iconSm),
                  color: AppColors.error,
                  onPressed: onDelete,
                ),
              ],
            ),
            const SizedBox(height: AppTokens.space8),
            _InfoChip(label: 'Dosage', value: medication.dosage),
            const SizedBox(height: AppTokens.space4),
            _InfoChip(label: 'Frequency', value: medication.frequency),
            const SizedBox(height: AppTokens.space4),
            _InfoChip(label: 'Duration', value: medication.duration),
            if (medication.instructions != null) ...[
              const SizedBox(height: AppTokens.space8),
              Container(
                padding: const EdgeInsets.all(AppTokens.space8),
                decoration: BoxDecoration(
                  color: AppColors.infoLight,
                  borderRadius: BorderRadius.circular(AppTokens.radiusXs),
                ),
                child: Row(
                  children: [
                    const Icon(
                      Icons.info_outline,
                      size: AppTokens.iconSm,
                      color: AppColors.info,
                    ),
                    const SizedBox(width: AppTokens.space8),
                    Expanded(
                      child: Text(
                        medication.instructions!,
                        style: AppTypography.bodySmall.copyWith(
                          color: AppColors.infoDark,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }
}

class _InfoChip extends StatelessWidget {
  final String label;
  final String value;

  const _InfoChip({required this.label, required this.value});

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        Text(
          '$label: ',
          style: AppTypography.bodySmall.copyWith(
            color: AppColors.textSecondary,
          ),
        ),
        Text(
          value,
          style: AppTypography.bodySmall.copyWith(
            fontWeight: FontWeight.w600,
          ),
        ),
      ],
    );
  }
}